### ISSUE TITLE
Collaborate 

### ISSUE THREAD

**Issue by ndelangen** [dennisreimann/uiengine#11]
Hey Dennis!

How are you? This looks like an awesome project you're working on!

Over at [Storybook](https://github.com/storybooks/storybook) we're working on something very similar, and we have pretty much the same goals!

Would you be interested in collaborating on it?

I've tried ui engine's test example, and got it to work after just a little bit of puzzling, and I'm really impressed with it supporting so many frameworks already. Storybook supports React, React Native, HTML + Web Components, Angular, Vue, Polymer, and there is work on a few others by the community of maintainers. 

Care for a chat?

**Comment by dennisreimann** [comment]
Hey Norbert, sure – how about having a chat this friday?

**Comment by ndelangen** [comment]
Yes, perfect! I think we're in the same time-zone? Evenings between 21:00 - 24:00 is good for me, I'm at https://www.vuejs.amsterdam/ thursday and friday.

**Comment by dennisreimann** [comment]
Alright, let's meet at 21:00 in https://appear.in/dennisreimann – have fun at the conference!
