### ISSUE TITLE
Custom script added to the uiengine.html template does not render

### ISSUE THREAD

**Issue by luisjmontoro** [dennisreimann/uiengine#28]
Hello Dennis!

I'm trying to add a custom script to the uiengine.html template but it's not rendering. It's like any change I make to the template does not render when building the application.

The config.js is correct, though.

Any ideas on why this might be failing?

Thanks!

**Comment by dennisreimann** [comment]
Where can I see and reproduce this?

**Comment by luisjmontoro** [comment]
It is currently happening on our repo: https://github.com/alfonsomorcuende/thonet 
Thanks a lot!

**Comment by dennisreimann** [comment]
Hey Luis, sorry, but I cannot find a custom script or template that uses one in there. What exactly do you mean? What are you trying to accomplish and in which way does it fail?

**Comment by luisjmontoro** [comment]
I’m sorry Dennis, it is on this specific branch:
https://github.com/alfonsomorcuende/thonet/tree/custom-script

I’m just trying to add a Google Analytics script, but it’s like the engine
ignores any change I make to the template when rendering it.

*Luis J. Montoro*
UX / UI Designer & Front-end Developer
@luisjmontoro

El 21 de septiembre de 2018 a las 8:46:44, Dennis Reimann (
notifications@github.com) escribió:

Hey Luis, sorry, but I cannot find a custom script or template that uses
one in there. What exactly do you mean? What are you trying to accomplish
and in which way does it fail?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dennisreimann/uiengine/issues/28#issuecomment-423431382>,
or mute the thread

**Comment by dennisreimann** [comment]
From what I can tell you don't seem to be rendering components. The "preview" template (uiengine.html) is used to embed the rendered html into a general page, which includes your scripts and styles.

It is not used for documentation pages, which you seem to be using exclusively. There is no way to inject scripts into the interface of the documentation, similar to the `ui.customStylesFile` config option. Nevertheless: It seems you want to track the visitors of your Design System website, right? If so, see the [config docs](https://uiengine.uix.space/basics/config/): 

> you can provide an `analyticsId` (from Google Analytics UA-XXX-X) to track the site

```js
module.exports = {
  name: 'Thonet',
  analyticsId: 'UA-125556157-1'

  // ... rest of the config
}
```

Does this help?

**Comment by luisjmontoro** [comment]
Thank you so much, it seems that it works. I checked the config docs before but I should have missed that line.  🙃

**Comment by dennisreimann** [comment]
> I checked the config docs before but I should have missed that line.

You know what – I had to search some myself. I knew it was in there, but thought it would be more intuitive to have this in the `ui` config section. I guess I'll move it there with the 2.0.

btw: Great job on your Design System docs – they look gorgeous!

**Comment by luisjmontoro** [comment]
Thank you so much!! :)) It is a work in progress idea yet :)
