### ISSUE TITLE
Question: Template Engine Extensions/Helpers?

### ISSUE THREAD

**Issue by mablae** [dennisreimann/uiengine#3]
Just posting for discussion and opinion:

How to work with template engine extensions? Like Twig has many helper libraries and 
I guess other engines have them too, for example a "money formatter" ?

Is the goal to not rely on them anymore for "simplicity" ?

**Comment by dennisreimann** [comment]
You can use them as before and need to configure them in the adapter. Have a look at the [pug adapter of the uiengineering website](https://github.com/dennisreimann/uiengineering/blob/uiengine/lib/uiengine/pug.js) for example. 

The note in the README is meant as a warning: I think the approach of having many helpers leads to "globals" in the templates which is oftentimes a hack that can and should be prevented.
