### ISSUE TITLE
Iframe not resizing properly after switching to jsx-adapter

### ISSUE THREAD

**Issue by MrAvantiC** [dennisreimann/uiengine#34]
Hey Dennis!

**Describe the bug**
I wanted to switch from the default template _uiengine.html_ to a template using the jsx-adapter.
While this seemed to work at first, I noticed that after switching the iFrame of the variant-previews does not resize properly anymore.
For some reasons this only happens in Chrome and Safari. In Firefox it still works as expected.

**To Reproduce**
I have a minimal example repo here:
https://github.com/MrAvantiC/uiengine-jsx-template-demo

The relevant commit is this one:
https://github.com/MrAvantiC/uiengine-jsx-template-demo/commit/60af39f3d8ae7d7693d4c36ea05a032f7edc0302

Any idea what could cause this to happen?

**Comment by MrAvantiC** [comment]
Hey,

the reason I was trying this was because - as you might have noticed in #29 - I was trying to get Styled-Components to work with UIEngine.
Now that it did work, I was contemplating on how to handle global styles and thought I'd try the way that the library offered to inject global styling.
Unfortunately that requires JSX and therefore causes the resizing error.

Since there does not seem to be an easy way to inject the doctype into the html it does not seem worth it though, so back to HTML/JSS I guess. ;)

Thanks for your help!

**Comment by dennisreimann** [comment]
Thanks for elaborating on that! Get back any time you encounter trouble or things that aren't clear, this is valuable feedback :)
