### ISSUE TITLE
Component/variants for a theme

### ISSUE THREAD

**Issue by skyafonsoc** [dennisreimann/uiengine#35]
Hi, I'm starting to use uiengine and I was wondering if there is a way to show a variant only for a specific theme? we have an exception for a card and I would like to maybe specify this in the component config instead of just hiding it in the other themes.

Thanks! 👍

**Comment by dennisreimann** [comment]
Hi Claudia,

Thanks for the feedback! Right now this isn‘t possible, but I might add it to the feature list. What would you imagine this to look like? Would this be part of the variant config in the component.config.js?
I‘m trying to figure out things like that from the users/devs perspective, that‘s why I‘m asking. Just go ahead an propose something that‘d fit your needs and we can discuss it :)

Cheers
Dennis

**Comment by dennisreimann** [comment]
I just remembered this: For [design tokens](https://uiengine.uix.space/advanced/design-tokens/) there is already the `theme` config option:

> Restricts display to only the given theme id. Can be used for categories and tokens.

I guess it'd be good to have the option to define an array.

**Comment by skyafonsoc** [comment]
Hi Dennis,

Yes, I was thinking about adding an array with the theme ids inside the variant config :)

Thanks!!

**Comment by dennisreimann** [comment]
Alright, I‘ll have a look :)

Just because I‘m curious: are you just testing the UIengine or do you already use it in production?

**Comment by dennisreimann** [comment]
For now it works just like for the tokens and you can use the `theme` option to restrict the display to the given theme id. I will consolidate this in a future release, deprecate both the variant and tokens `theme` option and will turn this into something like `onlyThemes`, which will be an array.

This will be part of the v2.0.5 release.
