### ISSUE TITLE
Lazy load iframe variants

### ISSUE THREAD

**Issue by therealpecus** [dennisreimann/uiengine#40]
**Is your feature request related to a problem? Please describe.**
When components have a high number of variants, the web page slows down to a crawl loading all of the iframes for the variants.

**Describe the solution you'd like**
We integrated Yall.js https://github.com/malchata/yall.js/ and patched the component template to lazy load the variant iframe. This, combined with the existing anchor navigation, allows to load only variants needed for display, speeding up the page considerably. We have pages with 30 to 40 variants (which means 10 ~ 15 variants over 3 themes).

**Describe alternatives you've considered**
None.

**Additional context**
We have a PR ready but would like to discuss the overall benefit for the project and/or additional use cases before submitting it. Of course we can open a PR to share the code. Let us know what would work best.

**Comment by dennisreimann** [comment]
Nice, I‘d like to have a look at this in a PR :)
