### ISSUE TITLE
Re-add component source code

### ISSUE THREAD

**Issue by therealpecus** [dennisreimann/uiengine#43]
**Describe the bug**
Since version v2.2.0 the rendered HTML code source is missing. This is a side effect of removing the rendered HTML from the state (it did bloat it), but does not allow to access the HTML code rendered from the adapter. This is useful for integrators and developers adopting the component in its final rendered output instead of the template technology

**To Reproduce**
1. `git checkout v2.1.0`
2. `yarn run test-project`
3. open http://localhost:3000/patterns/molecules/formfield/
4. click on _code_
5. see HTML panel with rendered output
6. `git checkout master`
7. repeat steps 2-4
8. no HTML panel is visible

**Expected behavior**
see the HTML code block

**Additional context**
It should be fairly easy to use the iframe content instead of the rendered part previously stored in the vuejs store to restore the code panel. it could be loaded dynamically when the panel is opened to avoid bloating the DOM. Something along `this.contentDocument.querySelector('#app').innerHTML`.

Again I will take a chance at it with a PR, but I'm overwhelmed right now and it'll take some time.

**Workaround**
Update documentation 😇

**Comment by dennisreimann** [comment]
Hey Matteo,

Good point. I removed this as we were having trouble with it bloating the state in a very large project, as you already noted. 

Right now I am also busy with other stuff, let‘s see that we address this like you suggested whenever one of us finds the time to do so!

Thanks for the high quality of the issues you bring up. This could also be picked up by someone else who finds the time and is willing to contribute. 

Cheers
Dennis

**Comment by dennisreimann** [comment]
For reference: here is the commit that removed this particular feature. 8042674026d6b0407e873f8ef5073ced640cfa85

**Comment by therealpecus** [comment]
Hi @dennisreimann I finally managed to spend some time on this.
There is an issue that I'd like to discuss, in order to make an informed and shared decision.

Previously the rendered HTML view of a component variant was sourced from the `content` part in the state. This has been pruned for performance reasons, so my proposal was to fetch the rendered HTML directly from the rendered document displayed in the preview iframe.
So far so good (I have a working implementation).

The preview HTML document is rendered with the full template. When rendering it, `<!-- uiengine:content -->` is replaced with the actual content from the adaptor. This means there are no information left in the HTML preview of what was the actual content and where it was inserted within the surrounding template.

One way to address this would be to patch https://github.com/dennisreimann/uiengine/blob/ba96f28a18f39198af5f819fad22b53f4e047e50/packages/core/src/builder.js#L116 in `generatePageWithTemplate()` to rewrap `content` with a comment directive, but this pollutes the HTML output.

It might not be necessarily bad, but there might be workflows that use the generated HTML in pipelines where the additional comment is not welcomed. We could solve this by having an option in configuration so that either the HTML code panel shows the whole template, as rendered ( including the template structure) or it shows the rendered content only, but in this case the generated HTML includes a comment directive wrapping it.

The configuration option would work at build time, there would be no changes for the ui Vue component. What's your opinion on this? It shouldn't take much to add this configuration part. Otherwise, the code is ready for review, displaying the full HTML rendered template.

**Comment by dennisreimann** [comment]
Hey Matteo, thanks for taking the time and implementing a solution. IMHO we can safely go with the first approach: I don‘t think there are cases in which we break things with that and the UIengine injects stuff like the BrowserSync script anyways (at least for the previews embedded in the iframes). You could do it similar to [that](https://github.com/dennisreimann/uiengine/blob/master/packages/core/src/uiengine.js#L159).

If this sounds good to you, please create a pull request and we will flesh out the details based on that 👌🏻
