### ISSUE TITLE
Local sample server JS crashes on load - r.index is undefined

### ISSUE THREAD

**Issue by Flixbox** [dennisreimann/uiengine#53]
**Describe the bug**
Accessing `localhost:3000` gives the error `r.index is undefined`. The UI admin page (Port 3001) works perfectly.

**To Reproduce**
Follow the steps in the example setup process up to `npx uiengine build --serve --watch`. 

**Expected behavior**
I can see a rendered page.

**Screenshots**
![image](https://user-images.githubusercontent.com/14835021/65944746-b0f73700-e432-11e9-9ead-68cac6af24b5.png)
![image](https://user-images.githubusercontent.com/14835021/65944747-b48abe00-e432-11e9-8430-57c0d106c41d.png)

**Comment by dennisreimann** [comment]
Are you running on Windows? For me it works (testing on a Mac) – can you provide a repo I can reproduce it with?

**Comment by Flixbox** [comment]
Yes, I am running on Windows. I can provide you with a repo, hold on a minute or two.

**Comment by Flixbox** [comment]
Here we go:

https://github.com/Flixbox/uiengine-bug-reproduction

**Comment by dennisreimann** [comment]
Ok, I'm not able to really test it on Windows and Travis-CI does not fully support the Windows builds, yet. Hence stuff gets broken from time to time – mostly related to the different file system path formats. 

Would you be willing to help fix this or did you just want to quickly check out the project? I'm sorry that it's broken though, I can take a look next week maybe.

**Comment by Flixbox** [comment]
The project was recommended to me by a coworker and I'm looking at it as an alternative to react-styleguidist for documenting my react projects. 

What would be required to fix this? It'd already be helpful to get a few sourcemaps to see where the error lies. Maybe it's a simple fix, I'd be willing to help with that :)

**Comment by dennisreimann** [comment]
I can reproduce this using a virtual machine and I'll take a closer look during the next days. Sorry for the inconvenience!

**Comment by dennisreimann** [comment]
Alright, for me it now works on Windows with the just released v2.5.7 – let me know if this also works for you :)

The test are now also working on Windows, though there are still some [minor failures on Travis](https://travis-ci.org/dennisreimann/uiengine/jobs/592241607) which I'll fix soon.

**Comment by Flixbox** [comment]
Awesome work, thank you! I'll make sure to try it tomorrow and give you some feedback.

**Comment by dennisreimann** [comment]
The tests now also pass on Travis, nevertheless the [build step still fails](https://travis-ci.org/dennisreimann/uiengine/jobs/592405150) due to a [problem in Travis](https://travis-ci.community/t/nodejs-hangs-on-windows/1492).
The windows build allows failures for now so that hopefully general errors on Windows will surface on my radar earlier now :)

**Comment by Flixbox** [comment]
Yup, I'm getting zero errors on my windows machine and the page renders wonderfully. Thank you!

**Comment by dennisreimann** [comment]
Alright, thanks for reporting this issue! 

Let me know how the UIengine works for you and in case you have ideas for improving it :)
