### ISSUE TITLE
Update iconography

### ISSUE THREAD

**Issue by CosAnca** [dennisreimann/uiengine#60]
**Is your feature request related to a problem? Please describe.**
Current icons used throughout the project have very thin strokes :)

**Describe the solution you'd like**
Having a new set of icons with a bit thicker stroke can make them stand out better.

**Additional context**
Refresh the overall look of the application.

**Comment by CosAnca** [comment]
@dennisreimann There seems to be a very large collection of icons (about 125 - under `ui/src/icons`) but only a handful of them seems to be actually used throughout the project. Do you think it might be ok to remove them as part of the iconography update and include only the ones that are actually in use?

**Comment by dennisreimann** [comment]
Yes, that's fine, let's clean up a bit :)
