### ISSUE TITLE
Update the default style of the tables

### ISSUE THREAD

**Issue by CosAnca** [dennisreimann/uiengine#61]
**Is your feature request related to a problem? Please describe.**
Current table styles don't create a good distinction of the table header from the table body.

**Describe the solution you'd like**
Update **elements.styl** file with slightly improved styles for the tables

**Additional context**
Refresh the overall look of the application.

**Comment by dennisreimann** [comment]
As the tables now span 100% of the width, the cell proportions aren't optimal.
 
![tables](https://user-images.githubusercontent.com/886/86757288-50d99500-c043-11ea-8171-cbd6a0765dc7.png)

**Comment by CosAnca** [comment]
Yes some cells are too wide, indeed. I agree is not optimal.

So, I was thinking either revert to the default width given by the content as previously, or add `table-layout: fixed` (as in the screenshot) which could slightly solve the cell proportions issues but would require addressing cell content alignment on some of them and if too many columns are in one table then the content in some of them could be quite narrow.

Please, let me know what your thoughts are about this.

![localhost_3000_test-project_documentation_tokens_variables_(Laptop with HiDPI screen)](https://user-images.githubusercontent.com/4587864/86758797-01439b00-c03c-11ea-8562-623e7352cd62.png)

**Comment by dennisreimann** [comment]
I think the easiest is to just remove the `width: 100%` and accept the minor visual annoyance of differently sized tables on a single page. IMHO readability trumps this and I wouldn't get too fancy/complex here.
